### ISSUE TITLE
Error when using demo data option

### ISSUE THREAD

**Issue by sachiwije** [epi2me-labs/wf-basecalling#19]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.0.1

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

V5.1.1

### Workflow Execution - CLI Execution Profile

None

### What happened?

I installed EPI2ME and tried running with 'Use demo data' option but keeps failing.

### Relevant log output

```shell
Aug-25 14:08:04.152 [main] DEBUG nextflow.cli.Launcher - $> /usr/lib/epi2me/resources/nextflow-all -log /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/nextflow.log run /mnt/nvmexpg1/epi2/workflows/epi2me-labs/wf-basecalling/main.nf -params-file /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/params.json -w /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/work -ansi-log false -offline -profile standard -with-weblog 'http://localhost:37687' -resume -name zen_poincare -c /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/demo.config -c /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/global.config
Aug-25 14:08:04.169 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.2
Aug-25 14:08:04.177 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/mnt/nvmexpg1/epi2/workflows/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.3
Aug-25 14:08:04.181 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Aug-25 14:08:04.181 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Aug-25 14:08:04.183 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Aug-25 14:08:04.186 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Aug-25 14:08:04.191 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /mnt/nvmexpg1/epi2/workflows/epi2me-labs/wf-basecalling/nextflow.config
Aug-25 14:08:04.192 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/demo.config
Aug-25 14:08:04.193 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/global.config
Aug-25 14:08:04.193 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/nvmexpg1/epi2/workflows/epi2me-labs/wf-basecalling/nextflow.config
Aug-25 14:08:04.193 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/demo.config
Aug-25 14:08:04.193 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/global.config
Aug-25 14:08:04.204 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Aug-25 14:08:04.499 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Aug-25 14:08:04.507 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Aug-25 14:08:04.511 [main] ERROR nextflow.cli.Launcher - Unable to parse config file: '/mnt/nvmexpg1/epi2/instances/wf-basecalling_b470a48b-c0b0-4c40-aabe-36f14b5db1e7/global.config'

  Compile failed for sources FixedSetSources[name='/groovy/script/Script94BEA6A9D20E10AD31914301CC5A18F0/_nf_config_c39cdad9']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  /groovy/script/Script94BEA6A9D20E10AD31914301CC5A18F0/_nf_config_c39cdad9: 2: Unexpected character: '#' @ line 2, column 1.
     #
     ^
  
  1 error

ch.artecat.grengine.except.CompileException: Compile failed for sources FixedSetSources[name='/groovy/script/Script94BEA6A9D20E10AD31914301CC5A18F0/_nf_config_c39cdad9']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/groovy/script/Script94BEA6A9D20E10AD31914301CC5A18F0/_nf_config_c39cdad9: 2: Unexpected character: '#' @ line 2, column 1.
   #
   ^

1 error

	at ch.artecat.grengine.code.groovy.DefaultGroovyCompiler.compile(DefaultGroovyCompiler.java:258)
	at ch.artecat.grengine.load.DefaultTopCodeCache.getUpToDateCode(DefaultTopCodeCache.java:80)
	at ch.artecat.grengine.load.LayeredClassLoader.getTopLoader(LayeredClassLoader.java:251)
	at ch.artecat.grengine.load.LayeredClassLoader.loadMainClass(LayeredClassLoader.java:202)
	at ch.artecat.grengine.engine.LayeredEngine.loadMainClass(LayeredEngine.java:198)
	at ch.artecat.grengine.Grengine.loadMainClass(Grengine.java:679)
	at ch.artecat.grengine.BaseGrengine.load(BaseGrengine.java:538)
	at ch.artecat.grengine.BaseGrengine.load(BaseGrengine.java:421)
	at ch.artecat.grengine.BaseGrengine$load.call(Unknown Source)
	at nextflow.config.ConfigParser.loadScript(ConfigParser.groovy:222)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:303)
	at nextflow.config.ConfigParser$parse$4.call(Unknown Source)
	at nextflow.config.ConfigBuilder.parse0(ConfigBuilder.groovy:435)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:421)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:371)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:316)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:803)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:816)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:321)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/groovy/script/Script94BEA6A9D20E10AD31914301CC5A18F0/_nf_config_c39cdad9: 2: Unexpected character: '#' @ line 2, column 1.
   #
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:148)
	at org.apache.groovy.parser.antlr4.AstBuilder.collectSyntaxError(AstBuilder.java:4321)
	at org.apache.groovy.parser.antlr4.AstBuilder.createParsingFailedException(AstBuilder.java:4304)
	at org.apache.groovy.parser.antlr4.AstBuilder.convertException(AstBuilder.java:261)
	at org.apache.groovy.parser.antlr4.AstBuilder.buildCST(AstBuilder.java:235)
	at org.apache.groovy.parser.antlr4.AstBuilder.buildAST(AstBuilder.java:269)
	at org.apache.groovy.parser.antlr4.Antlr4ParserPlugin.buildAST(Antlr4ParserPlugin.java:58)
	at org.codehaus.groovy.control.SourceUnit.buildAST(SourceUnit.java:256)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.codehaus.groovy.control.CompilationUnit.buildASTs(CompilationUnit.java:667)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:633)
	at ch.artecat.grengine.code.groovy.DefaultGroovyCompiler.compile(DefaultGroovyCompiler.java:229)
	... 64 common frames omitted
```

**Comment by SamStudio8** [comment]
@sachiwije Have you set a "Global nextflow config" in the EPI2ME application? It would appear to not be a valid Nextflow configuration file.

**Comment by sachiwije** [comment]
Thanks! Looks like I incorrectly added the nextflow installed path which resulted in the error. I removed it and working now. Is it necessary to have a Global nextflow config?

**Comment by SamStudio8** [comment]
@sachiwije That's great, I'm glad that's working now. A global Nextflow config is not required.
